### ISSUE TITLE
NullPointerException when retrieving the editor location

### ISSUE THREAD

**Issue by AlexJitianu** [odaata/HisTEI#17]
Hi,

Someone reported the exception from below. I think that what happens is that the code is invoked by Oxygen on a timer, after the editor is close (so there is no current editor).
The SchemaListProvider is already created lazy so I suggest to get the location at that particular moment, but by getting it from the context object (context.getSystemID()).

`java.lang.NullPointerException
    at info.histei.utils.OxygenUtils.getCurrentEditorLocation(OxygenUtils.java:213)
    at info.histei.extensions.HTSchemaManagerFilter.&lt;init&gt;(HTSchemaManagerFilter.java:23)
    at info.histei.HTExtensionsBundle.createSchemaManagerFilter(HTExtensionsBundle.java:52)
    at ro.sync.ecss.extensions.g.createSchemaManagerFilter(Unknown Source) `

**Comment by AlexJitianu** [comment]
We got another report with this NPE.

**Comment by AlexJitianu** [comment]
There is a fork that fixes this issue: https://github.com/oxygenxml/HisTEI
